[[extensions]]
name = "Create tickets action link"
description = "Create tickets"
handle = "ticket-create-action-link"
uid = "d03afec7-e4b4-ad9a-6a3a-e3f2918b1bca1a11a027"
type = "admin_link"

[[extensions.targeting]]
target = "admin.app.intent.link"
url = "/tickets/create"
tools = "./tools.json"
instructions = "./instructions.md"

[[extensions.targeting.intents]]
type = "application/ticket"
action = "create"
schema = "./ticket-create-schema.json"
